### ISSUE TITLE
How is your work come along?

### ISSUE THREAD

**Issue by deng-yongsheng** [bekmansurov/gree-hvac-protocol#1]

**Comment by damianmichna** [comment]
I have 4 Aermec SLG-250W and I think it is the same protocol. I got something like this:
'f886e600666060e680009800e0e68680000000060000000000000000000086600060e06000e08000000000000000f8'
'f88606fe066080000018007e0606e0180000000006fe'

**Comment by damianmichna** [comment]
UART between WIFI shows this (sniff on RX and TX):
b'7e7e2f01000000000090020200000000000000000000080000000000000000000000000000000000000000020200000000d0'
b'7e7e30310000400000900202000000000000000000000800000000000000000000000000000000000000000000003e0000007b'
b'7e7e1a0306000000000000000000007e78080629350000000000010086'
b'7e7e2f3400004000008028413e003e010000000000000000810000000000000000000000000000000000000000000000008a'
b'7e7e2f01000000000090020200000000000000000000080000000000000000000000000000000000000000020200000000d0'
b'7e7e30310000400000900202000000000000000000000800000000000000000000000000000000000000000000003e0000007b'
b'7e7e2f01000000000090020200000000000000000000080000000000000000000000000000000000000000020200000000d0'
b'7e7e30310000400000900202000000000000000000000800000000000000000000000000000000000000000000003e0000007b'
b'7e7e1a0304000000000000000000007e78080629360000000000010085'
b'7e7e2f35000040000000000000009600003837380000000000000000000000000000000000000000000000000000000000e1' 
b'7e7e2f01000000000090020200000000000000000000080000000000000000000000000000000000000000020200000000d0'
b'7e7e30310000400000900202000000000000000000000800000000000000000000000000000000000000000000003e0000007b'
b'7e7e30310000400000900202000000000000000000000800000000000000000000000000000000000000000000003e0000007b'

**Comment by deng-yongsheng** [comment]
It's awesome. I noticed your latest commit. It's a very meticulous work.
